In [ ]:
import numpy as np

A = np.array([[2, -1],
              [0,  3]])

B = np.array([[ 1,  2],
              [-3,  4]])



array([[ 3,  1],
       [-3,  7]])

In [24]:
sum = A + B
print("A+B=")
print(sum)



A+B=
[[ 3  1]
 [-3  7]]


In [25]:
AB=A@B
print("AB=")
print(AB)

AB=
[[ 5  0]
 [-9 12]]


In [29]:
result=3*A-2*B
print("3*A-2*B=")
print(result)


3*A-2*B=
[[ 4 -7]
 [ 6  1]]


In [27]:
determinant= np.linalg.det(A)
print("Det of A=")
print(determinant)

Det of A=
6.0


Here determinant of A is not zero hence it is invertible.

In [22]:
inv=np.linalg.inv(A)
print("A⁻¹ =")
print(np.round(inv,3))

A⁻¹ =
[[0.5   0.167]
 [0.    0.333]]


In [38]:
C = np.array([[ 4,  1],
              [-2,  1]])
eigenvalues, eigenvectors = np.linalg.eig(C)

print(f"λ1 = {eigenvalues[0]:}, λ2 = {eigenvalues[1]:}")
print("Eigenvectors=")
print(np.round(eigenvectors,3))




λ1 = 3.0, λ2 = 2.0
Eigenvectors=
[[ 0.707 -0.447]
 [-0.707  0.894]]


In [40]:
X = np.array([
    [1, 4, 1.5, 100],
    [1, 6, 2.0, 150]
])

y = np.array([20, 30])

In [49]:

car3 = np.array([1, 8, 3.0, 200])
price_car3 = car3 @ beta
print("The predicted price is",round(price_car3,3))



The predicted price is 40.001


The normal equation 
                                         β=(XTX)−1XTy
equires the matrix XTX to be invertible. In this problem, the feature matrix X contains four parameters(including the bias term) but only two data sampes are provided.As a result, the matrix XTX becomes singular and its inverse does not exist. Therefore, the normal equation cannot be applied directly. To overcome this issue, the Moore–Penrose pseudo-inverse is used instead, which allows computation of the coefficient vector even when the matrix is singular.
